name: Test Linux build

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - '[0-9]*'
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - '**/autoversion.h'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends -V g++ libsqlite3-dev libssl-dev

      - name: Build default
        run: |
          g++ --std=c++2a */*.cc *.cc -o signalbackup-tools -lcrypto -lsqlite3

    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: .
        name: signalbackup-tools
        path: ./signalbackup-tools
